//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finance_trial4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.EMIcards = new HashSet<EMIcard>();
            this.orders = new HashSet<order>();
        }
    
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public string phone_number { get; set; }
        public string user_email { get; set; }
        public string user_address { get; set; }
        public string bank_name { get; set; }
        public string IFSC_code { get; set; }
        public string account_number { get; set; }
        public int cardtype_id { get; set; }
        public Nullable<bool> haspaid { get; set; }
        public bool isapproved { get; set; }
        public string pan_number { get; set; }
        public System.DateTime customer_dob { get; set; }
    
        public virtual CardTypeMaster CardTypeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMIcard> EMIcards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
