//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finance_trial4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMIcard
    {
        public int EMIcard_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public int EMIcard_number { get; set; }
        public decimal used_credit { get; set; }
        public decimal remaining_credit { get; set; }
        public System.DateTime EMIcard_expiry { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
