//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finance_trial4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class financedbEntities9 : DbContext
    {
        public financedbEntities9()
            : base("name=financedbEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminMaster> adminMasters { get; set; }
        public virtual DbSet<CardTypeMaster> CardTypeMasters { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<EMIcard> EMIcards { get; set; }
        public virtual DbSet<EMItypeMaster> EMItypeMasters { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<productFAQ> productFAQs { get; set; }
        public virtual DbSet<productsMaster> productsMasters { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    }
}
