//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finance_trial4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productFAQ
    {
        public int productFAQ_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string question { get; set; }
    
        public virtual productsMaster productsMaster { get; set; }
    }
}
